query GetUserFollowers(
$pageSize:Int
$pageNumber:Int
$sortBy: String
$sortDirection: SortDirection
$userId: Int!
){
    getFollowers(
        pageSize: $pageSize
        pageNumber: $pageNumber
        sortBy: $sortBy
        sortDirection: $sortDirection
        userId: $userId
    ){
        pagesCount,
        page,
        pageSize,
        totalCount,
        items {
            id,
            userId,
            userName,
            firstName,
            lastName,
            createdAt
        }
    }
}