import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@radix-ui/themes/styles.css'
import './globals.css'
import { AlertsProvider } from '@/shared/ui'
import { Header } from '@/widgets/Header'
import { Toaster } from 'sonner'
import ApolloProvider from '@/app/providers/apollo/ApolloProvider'
import { AppWrapper } from '@/porocesses'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: {
    template: '%s | Inctagram',
    default: 'Inctagram',
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <ApolloProvider>
          <AlertsProvider>
            <Header />
            <main className={'main'}>
              <AppWrapper>{children}</AppWrapper>
              <Toaster />
            </main>
          </AlertsProvider>
        </ApolloProvider>
      </body>
    </html>
  )
}
